### ISSUE TITLE
Altre idee

### ISSUE THREAD

**Issue by Francescomele** [Davide-Perrone-655/Esame-Scientific-Programming#7]
1) DARE LA POSSIbilità di fare solo storie montecarlo
2) Dare la possiilità di utilizzare le storie montecarlo in archivio per calcolare le osservabili
3) controllare gli Y/N (unita temperatura)
4) formatting delle stringhe in standard output

**Comment by Francescomele** [comment]
5)rivedere errore del bootstrap 
6)boot_cycle
7)nspazzate

**Comment by Francescomele** [comment]
8)mettere piu cifre significative nei nomi dei files

**Comment by Davide-Perrone-655** [comment]
tutti risolti tranne il 2, apro un issue a parte
