### ISSUE TITLE
Usare le vecchie storie

### ISSUE THREAD

**Issue by Davide-Perrone-655** [Davide-Perrone-655/Esame-Scientific-Programming#8]
Potremmo completare la modalità 3, dove con le vecchie storie vengono calcolate le osservabili. Ci penseremo dopo la risposta del prof

**Comment by Davide-Perrone-655** [comment]
Progetto consegnato, potremmo anche chiudere l'issue @Francescomele

**Comment by Francescomele** [comment]
Se abbiamo tempo fra qualche settimana possiamo fare anche il wolf

Il giorno mer 26 mag 2021 alle 12:22 Davide-Perrone-655 <
***@***.***> ha scritto:

**Comment by Francescomele** [comment]
Scherzo

Il giorno mer 26 mag 2021 alle 13:03 Francesco Anna MELE <
***@***.***> ha scritto:
